app:
  name: Studnet Info App from Properties,prefix
  version: 1.0.2, prefix
  developers:
    - Ibrahim
    - Ayaz
  numbers:
    one: 1
    two: 2

server:
  port: 9091

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_CONNECTION_ADDR:localhost}:3306/ibrahim_db?createDatabaseIfNotExist=true&useSSL=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&zeroDateTimeBehavior=convertToNull&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
  jpa:
    open-in-view: false
#    properties:
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: "false"
#        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        format_sql: "true"
#    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
#    hibernate:
#      ddl-auto: validate
    show-sql: "true"
    liquibase:
      enabled: true